plugins {
    id 'com.google.devtools.ksp'
    id 'java-library'
    id 'kotlin'
    id 'kotlin-kapt'
}

kotlin {
    sourceSets {
        main.kotlin.srcDirs += 'build/generated/ksp/main/kotlin'
        test.kotlin.srcDirs += 'build/generated/ksp/test/kotlin'
    }
}

tasks.withType(JavaCompile) {
    options.compilerArgs << '-parameters'
    options.debug = true
    options.debugOptions.debugLevel = "source,lines,vars"
}

dependencies {
    kapt project(':tests-compiler')
    kapt deps.daggerCompiler
    implementation project(':core')
    implementation project(':lib')
    implementation deps.kotlin.stdlib
    implementation deps.test.truth
}